tmux-extrakto
Added `-J` to fix handling of wrapped lines (I mentioned this issue in item 4 [here](https://github.com/laktak/extrakto/issues/1#issuecomment-331310748))
Removed `-S` to capture only visible content. This is open for discussion, I personally think I'll never want to search and copy/insert something that I don't currently see on the screen, so this change will cleanup the suggestions list.
Opinions? 🙂
=> Improve pane contents retrieval

extrakto.py, tests/test_get_paths.py, tests/test_get_urls.py
Hi there, I noticed a bug on the pattern matching, not supporting UPPER CASE urls.
Also, I found out that there was no 'sftp' prefix on the regular expression for that matter.
I wondered which other cases I may be missing and I think that it would be a good idea to have tests to see what works and what doesn't. After starting with tests I realized that I had to make several changes to the code for them to work and be easily understandable.
I hope you don't mind the many changes I made to your code, if so, please let me know and I can fix whatever you think is best.
This doesn't require any extra dependency, you can run them as (for example) `python -m tests/test_get_urls`.
Here is an example output of what this PR adds:
```
➜ python -m tests/test_get_urls -v
test_match_HTTP …
```
=> Add tests for urls and paths

README.md, extrakto.tmux
Changes list:
* Group options together
* Make split direction and size configurable
I wanted to have more than the default 6 lines of height on the tmux window and I thought that it may be useful to have extrakto as a sidebar as well on some cases, so I went ahead and added configuration options.
This is how it looks with more height:
```
set -g @extrakto_window_split_direction 'v'
set -g @extrakto_window_lines "20"
```
This is how it looks as an horizontal sidebar:
```
set -g @extrakto_window_split_direction 'h'
set -g @extrakto_window_lines "50"
```
=> Add options

extrakto.tmux, scripts/helpers.sh, scripts/tmux-extrakto.sh
This seems to be the prefered way of getting options' values on other
plugins like tmux-copycat and tmux-yank.
Examples:
https://github.com/tmux-plugins/tmux-yank/blob/master/scripts/helpers.sh#L34
https://github.com/tmux-plugins/tmux-copycat/blob/master/copycat.tmux#L11
Besides being similar to how other plugins do this, which eases contributors entrance, this results in more readable and shorter configs.
=> Use helper script to get tmux options

README.md, extrakto.tmux, scripts/helpers.sh, scripts/tmux-extrakto.sh
So, this should tackle the proposed new option on #8.
Here are some thoughts about this implementation:
* We now have "default" values for options in two files: `extrakto.tmux` and `helpers.sh`
* When you use an horizontal extrakto you may end up shifting some lines upwards but I can't think of a reliable way of calculating how many extra lines we should add for that. This will vary on how long are the lines you're seeing by the time you open extrakto.
* Available configuration now can't be found in "just one file" as I liked to think before. This doesn't need to be a bad thing, it's just a nice thing we had before and now we don't. If we do want to have that we may need to think of a better way of managing configurations.
@maximbaz since you are our test user for this feature let me know …
=> Make grab area configurable using an option

extrakto.py, tests/test_get_words.py
Stripping `.` from both sides of a word does not handle hidden files, as I show in the test for hidden files. 
The correct way would be to only strip it from the end of the string, which is shown in the other test.
=> Match hidden files correctly in words mode

README.md
Here's an idea on how to show options differently.
Visually it takes a more space but I think that it is easier to read.
Current options:
Proposed options:
Thoughts?
=> Use table to show options

README.md, extrakto.py, scripts/tmux-extrakto.sh, tests/test_get_lines.py
I find it handy to copy entire lines of the screen (e.g. to copy an error message to the clipboard). Hence I wrote a small expansion.
Code changes
---
- add `get_lines()` function in `extracto.py`. Splits input text at newlines and strips whitespace.
- add command line option (`-l`, `--lines`), update tmux plugin accordingly (ctrl-f now cycles through three options)
=> Line extraktion feature

README.md, extrakto.tmux, scripts/helpers.sh, scripts/tmux-extrakto.sh
Sometimes I'm with a split of vim and a console. If editing in the vim pane, extrakto doesn't fuzzy find text/paths in the console pane. It would be great if it could do so. Meanwhile I have to select the target console pane, fuzzyfind there and copy, then get to the vim pane and paste.
=> multi pane fuzzy completion

README.md, scripts/helpers.sh, scripts/tmux-extrakto.sh
Added a fg_copy option. When fg_copy is set, $clip_tool runs in the foreground.
[More details about OSC 52](https://sunaku.github.io/tmux-yank-osc52.html).
=> Enable copying to terminals supporting the OSC-52 escape sequence

README.md, scripts/helpers.sh, scripts/open.sh
This is a quick-and-dirty implementation of allowing the user to
configure the popup size and position.
Popup size is set using `@extrakto_popup_size`, which takes a
comma-separated argument specifying width and height (in that order).
Popup position is set similarly using `@extrakto_popup_position` for the
x and y positions of the popup window, as in the description of
`display-menu` and `display-popup` in `man tmux`.
This implementation lacks (and sorely needs) input validation. It will
break as soon as the user chooses to provide only one of the width
or height. The same goes for the x/y positions.
I'm not a huge fan of the way I use `awk` to parse the options (do I
really need an `echo` there?), but it should be portable across
different versions of awk.
I'll update this pull request …
=> Allow configuration of popup size and position

scripts/extrakto.sh
In recent versions of WSL2, the `/proc/sys/kernel/osrelease` has changed -- the string "microsoft" can now be lower case.
```
> cat /proc/sys/kernel/osrelease
4.19.128-microsoft-standard
```
This one-word (nice!) PR fixes the error where extrakto tries to use `xclip` on WSL2.
=> Add support for WSL2

scripts/open.sh
If the tmux session window is resized while a popup is visible, the popup automatically terminates and `tmux popup` returns with exit code 129
This results in `tmux` displaying a full-pane error page `extrakto/open.sh failed with error code 129'.
This change ensures the popup is re-opened with the new (automatically scaled to the new window size by default) and avoids the tmux error pane.
Note that resizing the window will cause fzf to be re-launched, losing any existing search.
=> Ensure open.sh handles tmux-popup error return

scripts/open.sh
If you have remain-on-exit set to on, and use the split-window popup, you'll have a zombie window left over unless remain-on-exit is explicitly turned off.
=> Turn off remain-on-exit for the split-window popup.

extrakto.py
By default, ArgumentParser returns a string; however, in the case of --min-length, an integer is the type that is needed.
The original behaviour resulted in a TypeError exception:
`TypeError: '>=' not supported between instances of 'int' and 'str'`
=> extrakto.py: fix type for --min-length command line argument

scripts/open.sh
Extrakto fails with tmux-3.2-rc4:
```
$ ./.tmux/plugins/extrakto/scripts/open.sh
tmux: unknown option -- K
usage: display-popup [-CE] [-c target-client] [-d start-directory] [-h height] [-t target-pane] [-w width] [-x position] [-y position] [command]
```
-K is now default behavior:
https://github.com/tmux/tmux/commit/c44750792a9683c5cd6f9df5a69e7417b88772d2
=> Drop tmux display-popup -KR arguments

extrakto.tmux
The fix for this issue(#61), used a Bash 4 method of lowercasing the `extrakto_key` option.
This caused the plugin to crash on pre-4 Bash. This happens before the `Please update bash...` message.
This PR changes that syntax to a POSIX compliant mechanism of `tr`.
Reference:
https://stackoverflow.com/a/2264537/3395659
=> Use a POSIX compliant method of lowercasing instead of Bash 4 method.

README.md, scripts/extrakto.sh, scripts/helpers.sh
>  Originally from issue #72 [How to make the default filter as "lines"?].
>   but it seems better to generalize the config to not just simply let the
>   user define the "default" (or in fact the first) filter in the list, but
>   the whole filter list in order as well.
Feel free to comment on any change needed, I would really appreciate that. I wouldn't call myself a bash expert, most of the time I just use bash as my go-to quick fix duck tape so can't be confident what I wrote doesn't deviate much from best practices (if bash even has those). The readarray builtin for example was something I found convenient here, but it wasn't available until bash 4.0 or so, if backward compatibility with older bash versions was important for this project then I'd change it to good old read instead.
=> (Related to issue #72) Added configuration variable for defining the order of filter modes

README.md, scripts/extrakto.sh
Hey! I noticed that extrakto failed to detect the right clipboard tool on Wayland and updated the script to use `wl-copy` in that case.  I hope it helps!
=> Add support for Wayland (wl-copy)

HELP.md, scripts/extrakto.sh
The selection elements are joined by newlines (line mode), or spaces (other modes). To ensure the pasted text is not interpreted, `tmux paste-buffer` bracketed mode is now used.
Close #79.
=> add support for multiple selections

scripts/extrakto.sh
This uses the `-w` option for the `set-buffer` command which implements OSC 52 support. This fixes my issue in #92.
=> Utilise native support for OSC 52 with the -w option - Fixes #92

README.md, extrakto.py, scripts/extrakto.sh, scripts/helpers.sh
This is a reduced version of #103 
What this PR does:
Introduces `extrakto_fzf_unset_default_opts` in order to unset the environment variable `FZF_DEFAULT_OPS`.
I found out that certain operations would not work with my default `FZF_DEFAULT_OPS` value.
For example:
Having the option `-1` (or `--select-1`) will make `extracto`'s pop-up disappear immediately when there is 0 or just 1 match thus preventing you from switching to another filter.
Extra modes added:
- path
- url
- quote
- s-quote
Add `--word` as a parameter for the sake of consistency.
Before this PR:
```
set -g @extrakto_filter_order "url line quote s-quote word path all"
```
And no matter what you did, the filters would always be: `word all line`
Now calling `extracto` will give you the `url` filter as default as expected.
=> Add extra modes

HELP.md
Change 'grab are' to 'grab area' in the HELP.md file
=> fix typo for word 'area'

extrakto_plugin.py, scripts/open.sh
Bring feature parity with master: import functionality from #118
=> Import functionality from #118

HELP.md, extrakto.conf, extrakto.py, extrakto_plugin.py, tests/test_get_words.py
Currently, extracto uses the same minimum length for all filters. This PR introduces an optional config key to change the minimum length for each filter individually. The default value is still five, though.
=> Define minimum length per filter

extrakto_plugin.py
As explained in issue #125 if **appendWindowsPath** is disabled in /etc/wsl.conf, using the clip.exe executable directly is not possible. Switching to the full path fixes this and should work in all situations, regardless of appendWindowsPath.
=> Added full path for clip.exe for WSL (#125)

README.md, extrakto.py, extrakto_plugin.py
By default, extrakto_plugin is only showing alternative options to filters and prefixing the results with the name filter whenever we trigger the `all` filters option.
extrakto provides us the option to enable or disable both the filter alternatives and the prefixing of the names.
This code allows this option in our plugin.
The code has been modified to follow what was suggested by @laktak in his [comment](https://github.com/laktak/extrakto/pull/133#issuecomment-3104712525)
| Option                                | Default         | Description |
| :---                                  | :---:           | :--- |
| `@extrakto_alt`                       | `all`           | Show alternative filters. Possible values are: `all` to only show them for the all filter, `any` for any filter and …
=> feat: add @extrakto_alt and @extrakto_prefix_name options
